### ISSUE TITLE
Figure out how to get new issues all to be in cursorless-vscode

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless-vscode#468]
The obvious thing would be to disable them on cursorless-talon, but was worried then people wouldn't know where to file issues. Easy enough for me to just transfer them as they come, and could prob easily add some automation. GitHub leaves a nice redirect when you transfer

__Originally posted by @AndreasArvidsson in https://github.com/pokey/cursorless-talon/issues/147#issuecomment-1011504739__

**Comment by pokey** [comment]
@AndreasArvidsson WDYT?

**Comment by AndreasArvidsson** [comment]
And automatic transfer sounds like the best idea
If you disable the issues is their way to leave a message there instead?

**Comment by pokey** [comment]
I think I'm going to leave them on by default and transfer them manually as they come in.  It's super easy to do and results in a nice transparent redirect.  If moving these issues becomes a big time sink, I'll add automation.  I'd rather have people post them in the wrong place than get frustrated and not post them at all
