### ISSUE TITLE
The installation.md has a bad link to clone the cursorless-talon repo

### ISSUE THREAD

**Issue by AndrewDant** [cursorless-dev/cursorless-vscode#556]
installation.md has this link to clone the talon repo:
![image](https://user-images.githubusercontent.com/30133577/153721413-908f91aa-5df7-4818-9882-fee7f34315e0.png)

However trying to use that link gives a 400 error. I believe the issue is because it lacks .git at the end of the link as in the following copy/paste from the repo itself:
https://github.com/cursorless-dev/cursorless-talon.git

**Comment by pokey** [comment]
I don't believe the `.git` extension is necessary. Are you sure your credentials are set up for `https` remotes? Either way, if you go to https://github.com/cursorless-dev/cursorless-talon you can just click the big green clone button there and do whatever you usually do

**Comment by pokey** [comment]
Does it work for you with the `.git` extension but not without?

**Comment by AndrewDant** [comment]
It did work for me with that extension but not without. I was cloning in vscode though so maybe they just don't handle that right.

**Comment by pokey** [comment]
Strange. The knausj repo also uses the version without a `.git`. Did that one work for you?

I mean I guess I could just add the `.git`. Prob no harm in that

**Comment by pokey** [comment]
@AndreasArvidsson any reason for us not to use `.git` prefix?  I just copied from knausj

**Comment by AndreasArvidsson** [comment]
I don't really see a downside with using the suffix.
