### ISSUE TITLE
Add hats to tokens in the outline pane

### ISSUE THREAD

**Issue by DanGoesIntercept** [cursorless-dev/cursorless-vscode#568]
It would be very useful to have elements in the outline pane of Visual Studio Code get hats so that when I want to bring them into code, they are targetable like other in-buffer tokens. The token in the outline pane could be treated either as exactly what is listed within the pane (e.g. _someVariable, or Start()), or it could be the full statement that the outline element represents. This would allow you to bring, move, go to, and other actions that makes sense.

**Comment by pokey** [comment]
Hi @DanGoesIntercept! Yes, that would be awesome. Unfortunately, the VSCode api can be quite limiting. We don't have the ability to put hats in that part of the editor using the VSCode api 😕

The closest we are likely to be able to get is https://github.com/cursorless-dev/cursorless-vscode/issues/423

I can have another look at the api to see if anything has changed. Longer term, we'll probably be able to get there along a more generic route using either OCR or the accessibility tree, but both of those will require new functionality from talon, esp if we want them to operate cross-platform

**Comment by DanGoesIntercept** [comment]
Well that's disappointing, but make sense. Thanks for the response. This at least gives me a good reason to poke a bit through the source code for vscode & cursorless to see how it all fits together!

**Comment by pokey** [comment]
Yes, definitely a bummer; would love to have something like that myself.  I want hats everywhere 😊

I think I'll close this one for now, but we can reopen it once we get OCR / accessibility tree stuff working
