### ISSUE TITLE
Decorations don't scale with editor zoom

### ISSUE THREAD

**Issue by brxck** [cursorless-dev/cursorless-vscode#78]
I'm on 5271ce3f1c2d80fded9917826b4153d270351f1e and Ubuntu 20.10. 

VS Code info:

```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic
```

#### No Zoom

![no zoom](https://user-images.githubusercontent.com/28877984/124815744-7a5e2280-df1c-11eb-98e1-fd16d0bdfce3.png)

#### 5x Zoom

![5x zoom](https://user-images.githubusercontent.com/28877984/124815783-86e27b00-df1c-11eb-863e-e1b9ef0d8ba0.png)

**Comment by brxck** [comment]
This is the case on my new machine as well 😢

**Comment by pokey** [comment]
Weird! I believe that zoom level is a setting, so we could maybe read zoom level and adjust based on that.

Strange that it only happens for some VSCode setups. Does it happen on a clean VSCode instance with no extensions installed?

We could have a setting to toggle this correction and then mention it in known issues

**Comment by pokey** [comment]
@brxck when you get a minute, would be amazing if you could check whether https://github.com/pokey/cursorless-vscode/pull/273 fixes this one

**Comment by brxck** [comment]
@pokey unfortunately not 😦 

![Screenshot from 2021-09-11 10-08-24](https://user-images.githubusercontent.com/28877984/132955725-d407a91d-0763-40da-9376-24cba1ffd860.png)

![Screenshot from 2021-09-11 10-08-45](https://user-images.githubusercontent.com/28877984/132955727-a8171696-4a13-4a52-854c-fc710357763f.png)

**Comment by AndreasArvidsson** [comment]
Is this still a problem?

**Comment by brxck** [comment]
Yep, same behavior. Let me know if I can provide any other info/help!

<img width="356" alt="image" src="https://user-images.githubusercontent.com/28877984/145690180-970ad3ea-7675-4dbb-b943-fbe4189fbcaa.png">

**Comment by AndreasArvidsson** [comment]
This is so strange. We have tested this on the windows, linux, and mac and it works on all three except for on your computer.

**Comment by brxck** [comment]
Well I just realized something about this! Come to find out that there are two types of zoom actions in vscode.

`workbench.action.zoomIn` scales all UI. Cursorless deals with this as expected.

`editor.action.fontZoomIn` scales only the editor font. _This will trigger the issue._ These actions don't have any keybindings by default, but they are triggered on `ctrl`  + mousewheel over the editor.

**Comment by pokey** [comment]
ohh weird.  and that's different from increasing the font size?

**Comment by brxck** [comment]
Yep! Cursorless responds fine to font size changes. And apparently mousewheel zoom is a setting that is off by default? Don't remember turning that on... No wonder I'm the only person who's run into this 😅

**Comment by pokey** [comment]
Hmm.  I wonder if we should fix this one or just add a note to https://github.com/cursorless-dev/cursorless-vscode/wiki/Troubleshooting

**Comment by brxck** [comment]
Hardly seems worth fixing at this point. Especially after a brief poke around the extension API didn't yield an obvious way to get at this zoom level.

**Comment by pokey** [comment]
Ok added https://github.com/cursorless-dev/cursorless-vscode/wiki/Troubleshooting#decorations-dont-scale-with-editor-zoom.  Thanks for getting to the bottom of this one!
